### PR TITLE
edm arrows added

### PR DESCRIPTION
**Pull request by Gavin-L26**
Added arrows to level 2

Fixed some of the the obvious errors for: 
- platform placement, 
- fishtreat placement
- unwanted random actions

There is probably more errors and bugs, but I think it is at least pretty playable and not a mess of a level.

### CODE REVIEW

**Comment by Allerises** [comment]
Arrows are working, but I noticed a few issues;
- on my first and second run in the editor I got phantom inputs that caused oopses and randomly teleported my character forwards. I haven't been able to recreate this bug
- The first checkpoint is on a lower platform from the one you're coming from, and I feel like it's too close to the edge so if you accidentally jump you will miss it. It's fine if you want it that way but feels a bit mean since you never stomp in this level so your brain isn't trained to do it.
- There's a section where you go right-jump-right-jump a few times, I keep getting an extra jump here in mid-air as if the cat is colliding with something, it's happened a few time and gotten me killed.
- Right before the second check point there's a similar right-jump-right-jump section and I think there's a missing jump arrow here that leads onto the platform with the checkpoint itself.

I'll try my best to get screenshots for these shortly

**Comment by Allerises** [comment]
https://drive.google.com/file/d/1DihUtIgGIcEj6K3EDaUDyPd4tQOvW_no/view?usp=sharing

here's a link to a video. I wasn't able to capture the double jump, but this shows the missing arrow, the phantom oops on respawn at the checkpoint (it can happen in other places, but always seems to happen at this checkpoint) and the teleportation

**Comment by Gavin-L26** [comment]
> https://drive.google.com/file/d/1DihUtIgGIcEj6K3EDaUDyPd4tQOvW_no/view?usp=sharing
> 
> here's a link to a video. I wasn't able to capture the double jump, but this shows the missing arrow, the phantom oops on respawn at the checkpoint (it can happen in other places, but always seems to happen at this checkpoint) and the teleportation

Thanks, yeah this level is honestly all over the place, I'll try to fix as much as I can. I can edit the checkpoint and missing arrow problem in midi. Teleportation tho was implemented to actually never let the music desync, kinda weird that it teleport so far ahead.

**Comment by lilvedaes** [comment]
> https://drive.google.com/file/d/1DihUtIgGIcEj6K3EDaUDyPd4tQOvW_no/view?usp=sharing
> 
> here's a link to a video. I wasn't able to capture the double jump, but this shows the missing arrow, the phantom oops on respawn at the checkpoint (it can happen in other places, but always seems to happen at this checkpoint) and the teleportation

I think it's important to fix these but we can do it after Level-Up, I don't think we have time for them. And the teleportation one surprisingly is a feature and not a bug jeje

**Comment by lilvedaes** [comment]
> > https://drive.google.com/file/d/1DihUtIgGIcEj6K3EDaUDyPd4tQOvW_no/view?usp=sharing
> > here's a link to a video. I wasn't able to capture the double jump, but this shows the missing arrow, the phantom oops on respawn at the checkpoint (it can happen in other places, but always seems to happen at this checkpoint) and the teleportation
> 
> Thanks, yeah this level is honestly all over the place, I'll try to fix as much as I can. I can edit the checkpoint and missing arrow problem in midi. Teleportation tho was implemented to actually never let the music desync, kinda weird that it teleport so far ahead.

awesome, let us know when it's updated to check it out again. We'll be on the GO train so there should be wifi.

**Review by lilvedaes — APPROVED** [review]
LGTM!!

**Pull request merged**
