### PR TITLE
Collision check

### PR DESCRIPTION
**Pull request by Gavin-L26**
- Added colour change to the arrows depending when player gets purrfect/nice/oops
- Resized collider for checkpoint and fish treat, eliminated the possibility that the player may not correctly interact with them
- Refactored PlayerMovement script code

### CODE REVIEW

**Review by lilvedaes — CHANGES_REQUESTED** [review]
Color changing is not working for me. I'll get Aamir to check it out as well.
Everything else seems to be working well though c:

**Comment by Allerises** [comment]
Very rarely I can get an oops right after passing an arrow and hitting a perfect/nice on it

Arrows only turn green on perfect/nice/oops, they also intermittently stop working, mainly on the jump arrows.

Fish are all collectible now, but it doesn't feel like a bonus challenge, you just spam shift on kb and get them all pretty easily between the arrows

**Comment by Gavin-L26** [comment]
> Color changing is not working for me. I'll get Aamir to check it out as well. Everything else seems to be working well though c:

That's weird, I don't really know where that problem might be. Do you want to check if there is any parameter that is missing in inspector section of the action managers (ActionJump, ActionSide, and ActionStromp)?

**Comment by Gavin-L26** [comment]
> Very rarely I can get an oops right after passing an arrow and hitting a perfect/nice on it
> 
> Arrows only turn green on perfect/nice/oops, they also intermittently stop working, mainly on the jump arrows.
> 
> Fish are all collectible now, but it doesn't feel like a bonus challenge, you just spam shift on kb and get them all pretty easily between the arrows

The colour only changing green bug is fixed. Can you show me on what condition the colour changing is not working? I'm having a hard time trying to recreate it. 

For fish collectibles, the decision we made is that we don't want the player to actually loose point if they didn't get them. Like you said, currently we can spam the eat button to get them, but I don't think it's too big of a problem. Especially when we get to level 2, the game itself is already very hard that even spamming eat button is difficult. 
We can implement a cooldown interval between each eat but we also have a lot of fish that are close together, which means intervals can only be very short anyway. In addition we have to implement some visual to indicate cooldown which I don't think we currently have time for. Do you have any suggestions on what may be good?

**Comment by Allerises** [comment]
> Can you show me on what condition the colour changing is not working? I'm having a hard time trying to recreate it.

I can't access my PC to test it out rn unfortunately, but from memory the issue happened after I missed a couple of arrows, they seemed to almost desync and then sometimes it seemed to sort itself out again.

> Do you have any suggestions on what may be good?

I think Daniela mentioned that we could change the placement of the fish to make them less common and a little more difficult / inconvenient to get and I thought that was a good idea, but I know they're placed according to the music so that might not be entirely feasible to do. I also agree it's not the end of the world if we leave it as-is.

**Comment by Gavin-L26** [comment]
> > Can you show me on what condition the colour changing is not working? I'm having a hard time trying to recreate it.
> 
> I can't access my PC to test it out rn unfortunately, but from memory the issue happened after I missed a couple of arrows, they seemed to almost desync and then sometimes it seemed to sort itself out again.
> 
> > Do you have any suggestions on what may be good?
> 
> I think Daniela mentioned that we could change the placement of the fish to make them less common and a little more difficult / inconvenient to get and I thought that was a good idea, but I know they're placed according to the music so that might not be entirely feasible to do. I also agree it's not the end of the world if we leave it as-is.

The colour changing should be working even when the arrows are missed now. Pls check again thanks

**Review by lilvedaes — APPROVED** [review]
LGTM!!

**Pull request merged**
